### ISSUE TITLE
Forward flags to clang-format

### ISSUE THREAD

**Issue by bbrk24** [wasm-fmt/clang-format#26]
I have been using the `clang-format` package, which is obsolete, and I've been looking for replacements. This one caught my eye recently for being used by node itself. However, it doesn't work for my use case.

I have a script that expects the `clang-format` command to be either the exact same as or a thin wrapper around the actual clang-format binary, and passes it flags such as `--dry-run` and `--Werror`. I was quite surprised when doing that with this package causes a `TypeError` of all things!

Will this package support forwarding flags like these, or is that out of scope for this project?

**Comment by magic-akari** [comment]
This is one of the objectives of this project.

This project has two objectives:
1. To provide a simple string-to-string function devoid of IO operations for direct use in browsers.
2. To offer a drop-in alternative to the original clang-format, leveraging wasm to achieve better cross-platform capabilities than the original clang-format.

Currently, the first objective has been achieved, and the second objective is to wrap the `format` function and re-implement it in node.

I am considering directly compiling and exporting the `main` function from the original `clangFormat.cpp` to reduce the cost of maintenance.

**Comment by bbrk24** [comment]
I just tried again with the new release, and got this absolutely massive syntax error:

[log.txt](https://github.com/user-attachments/files/17081514/log.txt)

`npx clang-format` gives me a syntax error right away, but `node node_modules/.bin/clang-format` doesn't. I think it might be trying to execute the JS as bash? The file doesn't appear to have a shebang, unlike the neighboring `clang-format-diff`.

**Comment by magic-akari** [comment]
You are right, it lacks the shebang.

**Comment by magic-akari** [comment]
The upcoming LLVM repository version is 20; I'm unsure if releasing a 19.1.1 is advisable.
I hope there's no version number conflict with the LLVM repository.
