### ISSUE TITLE
Incomplete output when source files are large

### ISSUE THREAD

**Issue by legendecas** [wasm-fmt/clang-format#27]
Refs: https://github.com/nodejs/node/pull/54994

When the source files are large, the outputs will be incomplete, like `env.cc` (81K) or `node_contextify.cc` (69K).

**Comment by magic-akari** [comment]
The solution is to avoid manually calling `process.exit` or to call it after stdout is flushed.

However, I now intend not to fix it this way. 
Considering the maintenance costs,  I'll directly compile the original `clangFormat.cpp`, which will ensure full support for the original CLI features.
